version: '3.8'

services:
  app:
    image: 'docker-spring-boot-postgres:latest'
    build:
      context: .
    container_name: app
    depends_on:
      - db
      - db-pgadmin
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/postgres
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - SPRING_JPA_HIBERNATE_DDL_AUTO=validate
    ports:
      - '8080:8080'

  db:
    image: 'postgres:17.6-alpine'
    container_name: db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data

  db-pgadmin:
    image: 'dpage/pgadmin4:latest'
    container_name: db-pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=123@localhost.com
      - PGADMIN_DEFAULT_PASSWORD=123
      - PGADMIN_CONFIG_ENHANCED_COOKIE_AUTH=False
    ports:
      - '80:80'
    volumes:
      - pgadmin_data:/var/lib/pgadmin

volumes:
  pgadmin_data:
  pgdata: